# Generated by Django 3.0.5 on 2020-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
