# Generated by Django 3.0.5 on 2020-05-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200506_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='date_of_delivery',
            new_name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='first_name',
        ),
    ]
