# Generated by Django 3.0.5 on 2020-05-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200510_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='MaterialRequests',
        ),
    ]
