# Generated by Django 3.0.5 on 2020-05-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200511_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_provider', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('price', models.CharField(max_length=50)),
                ('wantlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.MaterialRequests')),
            ],
        ),
    ]
