# Generated by Django 3.0.5 on 2020-05-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='wantlist_item',
        ),
    ]
